
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-nginx-ingress
  namespace: nginx-ingress
spec:
  allowedCapabilities:
    - NET_BIND_SERVICE
  privileged: false
  allowPrivilegeEscalation: true
  # Allow core volume types.
  volumes:
    - configMap
    - secret
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: MustRunAs
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  seLinux:
    rule: RunAsAny

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-nginx-ingress
  namespace: nginx-ingress
rules:
- apiGroups: [policy]
  resources: [podsecuritypolicies]
  verbs: [use]
  resourceNames: [psp-nginx-ingress]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-nginx-ingress
  namespace: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-nginx-ingress
subjects:
- kind: ServiceAccount
  name: default
  namespace: nginx-ingress
- kind: ServiceAccount
  name: nginx-ingress
  namespace: nginx-ingress
